-- CREACION TABLA log_alumno --

USE sistemaescolar_taddeocordoba

-- CREACION DE LA TABLA LOG DE AUDITORIA DE ALUMNO --
CREATE TABLE `sistemaescolar_taddeocordoba`.`log_alumno` (
  `ID_LOG` INT NOT NULL AUTO_INCREMENT,
  `ACCION` VARCHAR(45) NOT NULL,
  `USUARIO` VARCHAR(45) NOT NULL,
  `DETALLE` VARCHAR(45) NOT NULL,
  `FECHA` DATETIME NOT NULL,
  PRIMARY KEY (`ID_LOG`));

-- CREACION DEL LOG DE AUDITORIA DE ELIMINACION DE LA TABLA ASISTENCIA_CURSADA TRIGGER 2 –-

DELIMITER $$
CREATE TRIGGER log_before_delete_alumno
BEFORE DELETE ON alumno 
FOR EACH ROW
BEGIN
	INSERT INTO log_alumno (id_log, accion, usuario, detalle, fecha)
	VALUES (NULL, 'DELETE', SYSTEM_USER(), CONCAT ('SE ELIMINÓ EL ALUMNO', ID_LOG, 'PARA EL ALUMNO'), NOW());
END
 $$
DELIMITER ;